port: 4007
logFileRotate: 1d

production: sxdqt
version: v1.0
env: production

security:
  key: pecorino security key

etcd:
  cluster: etcd01.pecorino.org.cn:2379,etcd02.pecorino.org.cn:2379,etcd03.pecorino.org.cn:2379
